M48
; DRILL file {KiCad 9.0.7} date 2026-05-22T17:04:58-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-22T17:04:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.785
%
G90
G05
T1
X99.7Y-25.0
X99.7Y-130.0
X257.5Y-25.0
X257.5Y-130.0
T2
X236.31Y-65.5
M30
